# Generated by Django 6.0.2 on 2026-03-12 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('new_member', 'New Member'), ('rmd', 'RMD'), ('admin', 'Admin')], default='new_member', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='upline_rmd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downline', to=settings.AUTH_USER_MODEL),
        ),
    ]
