# Generated by Django 6.0.2 on 2026-03-12 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_role_alter_customuser_upline_rmd'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_rmd',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('New Member', 'New Member'), ('RMD', 'RMD'), ('Admin', 'Admin')], default='New Member', max_length=50),
        ),
    ]
