# Generated by Django 6.0.2 on 2026-03-15 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pendinguser'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinguser',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=10),
        ),
    ]
