# Generated by Django 6.0.2 on 2026-03-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_pendinguser_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendinguser',
            name='status',
        ),
        migrations.AddField(
            model_name='pendinguser',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
