# Generated by Django 6.0.2 on 2026-03-26 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_pendinguser_status_pendinguser_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
