# Generated by Django 6.0.2 on 2026-05-12 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customuser_password_reset_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidHGICode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
