# Generated by Django 6.0.2 on 2026-06-05 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_protectedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_rmd_member',
            field=models.BooleanField(default=False),
        ),
    ]
