# Generated by Django 6.0.2 on 2026-06-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_customuser_is_rmd_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_receive_requests',
            field=models.BooleanField(default=False),
        ),
    ]
