# Generated by Django 6.0.2 on 2026-06-05 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_customuser_can_receive_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='RMDProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('hgi_code', models.CharField(max_length=50, unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rmd_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
