# Generated by Django 6.0.2 on 2026-06-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rmdprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='validhgicode',
            name='upline_rmd_hgi_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
