# Generated by Django 6.0.2 on 2026-06-08 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_add_upline_rmd_hgi_code_to_valid_hgi_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validhgicode',
            name='upline_rmd_hgi_code',
        ),
    ]
