# Generated by Django 6.0.2 on 2026-06-29 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_backfill_rmd_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='granted_pages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
