# Generated by Django 6.0.2 on 2026-07-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_protectedfile_slug_populate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='certifications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('New Member', 'New Member'), ('Licensed', 'Licensed'), ('RMD', 'RMD'), ('Admin', 'Admin')], default='New Member', max_length=50),
        ),
    ]
