from django.urls import path
from . import views

urlpatterns = [
    path('students/', views.studentsView),
    path('students/<int:pk>/', views.studentDetailView),
    path('login/', views.login_view),
    path('rmds/', views.rmd_list),
    path('register/', views.register_request),
    path('approve/<str:token>/', views.approve_request),
    path('deny/<str:token>/', views.deny_request),
    path('verify-token/<str:token>/', views.verify_token),
    path('check-username/', views.check_username),
    path('setup-account/', views.setup_account),
    path('forgot-password/', views.forgot_password),
    path('verify-reset-token/<str:token>/', views.verify_reset_token),
    path('reset-password/', views.reset_password),
    path('logout/', views.logout_view),
    path('users/', views.user_list),
    path('pending-users/', views.pending_users_list),
    path('pending-users/<int:pk>/', views.pending_user_detail),
    path('pending-users/<int:pk>/approve/', views.approve_pending),
    path('rmd-profiles/', views.rmd_profiles_list),
    path('rmd-profiles/<int:pk>/', views.rmd_profile_detail),
    path('users/<int:pk>/delete/', views.delete_user),
    path('users/<int:pk>/role/', views.change_user_role),
    path('users/<int:pk>/toggle-active/', views.toggle_active),
    path('users/<int:pk>/toggle-requests/', views.toggle_requests),
    path('rmd/members/', views.rmd_member_list),
    path('rmd/pending/', views.rmd_pending_list),
    path('hgi-codes/', views.hgi_codes_list),
    path('hgi-codes/<int:pk>/', views.hgi_code_detail),
    path('files/', views.file_list),
    path('files/<int:pk>/stream/', views.file_proxy),
]